version: '2'
services:
    exchange:
        build: python
        image: exchange
        ports: 
            - "6789:6789"
        networks:
            - default
    webserver:
        build: react
        image: webserver
        depends_on:
            - exchange 
        networks:
            - default
        ports:
            #- "8080:8080"
            - "3000:3000"
        volumes:
            - ./react:/html
