version: '2'
services:
    exchange:
        image: exchange
        ports: 
            - "6789:6789"
        networks:
            - default
    webserver:
        image: webserver
        depends_on:
            - exchange 
        networks:
            - default
        ports:
            - "8080:8080"
        volumes:
            - ./javascript:/html
