version: '2'
services:
    exchange:
        image: exchange
        networks:
            - default
    webserver:
        image: node
        depends_on:
            - exchange 
        networks:
            - default
        ports:
            - "8080:8080"
        volumes:
            - ./javascript:/html
