version: '2'
services:
    exchange:
        build: python
        image: exchange
        ports: 
            - "6789:6789"
        networks:
            - default
    webserver:
        build: react
        image: webserver
        depends_on:
            - exchange 
        networks:
            - default
        ports:
            - "8000:8000"
            - "3000:3000"
        environment:
            # debug or prod
            - MODE=debug
        volumes:
            - ./react:/html
