FROM rabbitmq:3.7.8

RUN rabbitmq-plugins enable rabbitmq_management

#RUN rabbitmqctl add_user admin admin
#RUN rabbitmqctl set_user_tags admin administrator
#RUN rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
